/* NEON VAULT Master features: progress, quests, notifications, reporting UI. */
(()=>{
 'use strict';
 const API='https://renderneon.souldreams.blitz.cloud/api';
 const TOKEN='nv_api_token';
 const $=s=>document.querySelector(s);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function call(path,opts={}){
  const token=sessionStorage.getItem(TOKEN)||'';
  const r=await fetch(API+path,{...opts,mode:'cors',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opts.headers||{})}});
  let data={};try{data=await r.json()}catch{}
  if(!r.ok)throw new Error(data.error||`Ошибка сервера (${r.status})`);
  return data;
 }
 function toastMsg(s){if(typeof window.toast==='function')window.toast(s);else{const t=$('#toast');if(t){t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}else alert(s)}}
 const iconFor=id=>({visit:'🌱',play3:'🎲',social:'💬'}[id]||'✦');
 window.renderMasterProgress=async function(){
  const q=$('#dailyQuestGrid'),a=$('#achievementGrid');if(!q||!a)return;
  q.innerHTML='<div class="empty-state">Загружаем задания…</div>';a.innerHTML='<div class="empty-state">Загружаем достижения…</div>';
  try{
   const d=await call('/progress');
   $('#progressLevel').textContent=d.level||1;$('#progressXp').textContent=(d.xp||0)+' XP';
   const claimed=d.quests.filter(x=>x.claimed).length;
   q.innerHTML=d.quests.map(x=>`<article class="master-item ${x.claimed?'is-done':''}"><div class="master-item-icon">${iconFor(x.id)}</div><div class="master-item-copy"><b>${esc(x.title)}</b><p>${esc(x.description)}</p><div class="master-meter"><i style="width:${Math.min(100,Math.floor((x.current/Math.max(1,x.progress))*100))}%"></i></div><small>${Math.min(x.current,x.progress)} / ${x.progress} · награда ${x.reward.toLocaleString('ru')} 🪙</small></div><button class="btn ${x.claimed?'ghost':''}" data-claim-quest="${esc(x.id)}" ${x.claimed||x.current<x.progress?'disabled':''}>${x.claimed?'Получено':'Забрать'}</button></article>`).join('')||'<div class="empty-state">Заданий пока нет.</div>';
   const unlocked=d.achievements.filter(x=>x.unlocked).length;$('#achievementCount').textContent=`${unlocked} / ${d.achievements.length} ОТКРЫТО`;
   a.innerHTML=d.achievements.map(x=>`<article class="master-achievement ${x.unlocked?'unlocked':'locked'}"><span class="master-achievement-icon">${x.unlocked?esc(x.icon):'◇'}</span><b>${esc(x.name)}</b><p>${esc(x.description)}</p><small>${x.unlocked?'Открыто · '+new Date(x.unlockedAt).toLocaleDateString('ru'):'Ещё впереди'}</small></article>`).join('');
  }catch(e){q.innerHTML=`<div class="empty-state">Не удалось загрузить задания: ${esc(e.message)}</div>`;a.innerHTML='<div class="empty-state">Проверь подключение к серверу и войди в аккаунт.</div>'}
 };
 document.addEventListener('click',async e=>{
  const b=e.target.closest('[data-claim-quest]');if(!b)return;
  b.disabled=true;try{const d=await call('/progress/quests/'+encodeURIComponent(b.dataset.claimQuest)+'/claim',{method:'POST',body:'{}'});toastMsg(`Получено ${d.reward} монет!`);await window.renderMasterProgress()}catch(err){toastMsg(err.message);b.disabled=false}
 });
 document.addEventListener('submit',async e=>{
  if(e.target.id!=='masterReportForm')return;e.preventDefault();
  const target=$('#reportTarget').value.trim(),reason=$('#reportReason').value,details=$('#reportDetails').value.trim();
  try{await call('/reports',{method:'POST',body:JSON.stringify({targetId:target,reason,details})});e.target.reset();toastMsg('Жалоба отправлена команде модерации. Спасибо.')}catch(err){toastMsg(err.message)}
 });
 // Server-backed privacy controls, notifications, live leaderboard and moderation queue.
 const prettyWhen=ts=>{const n=Number(ts);return n?new Date(n).toLocaleString('ru',{dateStyle:'short',timeStyle:'short'}):''};
 window.loadVaultPrivacy=async function(){const status=$('#privacyStatus');if(!status)return;try{const d=await call('/privacy');$('#privacyProfile').value=d.privacy.profile_visibility;$('#privacyComments').value=d.privacy.allow_comments;$('#privacyDm').value=d.privacy.allow_dm;status.textContent='Настройки загружены с сервера.'}catch(e){status.textContent=e.message}};
 document.addEventListener('submit',async e=>{if(e.target.id!=='vaultPrivacyForm')return;e.preventDefault();const status=$('#privacyStatus');status.textContent='Сохраняем…';try{const d=await call('/privacy',{method:'PATCH',body:JSON.stringify({profile_visibility:$('#privacyProfile').value,allow_comments:$('#privacyComments').value,allow_dm:$('#privacyDm').value})});$('#privacyProfile').value=d.privacy.profile_visibility;$('#privacyComments').value=d.privacy.allow_comments;$('#privacyDm').value=d.privacy.allow_dm;status.textContent='Приватность сохранена.';toastMsg('Настройки приватности сохранены.')}catch(err){status.textContent=err.message;toastMsg(err.message)}});
 let noticePanel=null;
 function ensureNoticePanel(){if(noticePanel)return noticePanel;noticePanel=document.createElement('aside');noticePanel.id='vaultNoticePanel';noticePanel.className='vault-notice-panel';noticePanel.hidden=true;noticePanel.setAttribute('aria-label','Уведомления');noticePanel.innerHTML='<div class="vault-notice-head"><div><span class="eyebrow">YOUR INBOX</span><h3>Уведомления</h3></div><button type="button" class="btn ghost" id="vaultNoticeClose" aria-label="Закрыть">✕</button></div><div id="vaultNoticeItems" class="vault-notice-items"><div class="empty-state">Загрузка…</div></div><button type="button" class="btn ghost full" id="vaultNoticeReadAll">Обновить и отметить прочитанным</button>';document.body.appendChild(noticePanel);return noticePanel;}
 async function refreshVaultNotifications(open=false){const btn=$('#vaultNotifyBtn');if(!btn||!apiToken())return;try{const d=await call('/notifications');const count=Number(d.unread)||0,badge=$('#vaultNotifyCount');badge.hidden=!count;badge.textContent=count>99?'99+':String(count);btn.classList.toggle('has-unread',count>0);if(open){const panel=ensureNoticePanel(),list=$('#vaultNoticeItems');panel.hidden=false;panel.classList.add('open');list.innerHTML=(d.notifications||[]).map(n=>`<article class="vault-notice ${n.read_at?'read':'unread'}"><span class="vault-notice-dot"></span><div><b>${esc(n.title)}</b><p>${esc(n.body||'')}</p><small>${esc(prettyWhen(n.created_at))}</small></div></article>`).join('')||'<div class="empty-state">Пока тихо. Новые события появятся здесь.</div>';try{await call('/notifications/read',{method:'POST',body:JSON.stringify({ids:(d.notifications||[]).filter(n=>!n.read_at).map(n=>n.id)})});badge.hidden=true;btn.classList.remove('has-unread')}catch{}}}catch(e){if(open)toastMsg(e.message)}}
 $('#vaultNotifyBtn')?.addEventListener('click',()=>{const p=ensureNoticePanel();if(!p.hidden){p.hidden=true;p.classList.remove('open')}else refreshVaultNotifications(true)});
 document.addEventListener('click',e=>{if(e.target.closest('#vaultNoticeClose')){noticePanel.hidden=true;noticePanel.classList.remove('open')}if(e.target.closest('#vaultNoticeReadAll'))refreshVaultNotifications(true);if(noticePanel&&!e.target.closest('#vaultNoticePanel')&&!e.target.closest('#vaultNotifyBtn')){noticePanel.hidden=true;noticePanel.classList.remove('open')}});
 window.loadVaultServerTop=async function(){const box=$('#serverTopList'),metric=$('#serverTopMetric');if(!box||!metric)return;box.innerHTML='<div class="empty-state">Загружаем рейтинг…</div>';try{const d=await call('/leaderboard?metric='+encodeURIComponent(metric.value));box.innerHTML=(d.rows||[]).map(r=>`<article class="server-top-row ${r.rank===1?'first':''}"><span class="server-top-rank">${r.rank===1?'🥇':r.rank===2?'🥈':r.rank===3?'🥉':'#'+r.rank}</span><div class="server-top-player"><b>${esc(r.name)}</b><small>${esc(r.role==='owner'?'👑 Владелец':r.role==='moderator'?'🛡 Модератор':r.premium?'✦ Premium':'Игрок')}</small></div><strong>${Number(r.value||0).toLocaleString('ru')}</strong></article>`).join('')||'<div class="empty-state">Пока нет зарегистрированных игроков.</div>'}catch(e){box.innerHTML=`<div class="empty-state">${esc(e.message)}. Войди в аккаунт и попробуй снова.</div>`}};
 $('#serverTopMetric')?.addEventListener('change',()=>window.loadVaultServerTop());
 document.addEventListener('click',async e=>{if(e.target.closest('#adminReportsBtn')){const box=$('#adminReportsList');box.innerHTML='<div class="empty-state">Загрузка жалоб…</div>';try{const d=await call('/admin/reports');box.innerHTML=(d.reports||[]).map(r=>`<article class="vault-report-row"><div><b>${esc(r.reporter_name)} → ${esc(r.target_name)}</b><p>${esc(r.reason)} · ${esc(r.details||'Без подробностей')}</p><small>${esc(prettyWhen(r.created_at))} · ${esc(r.status)}</small></div>${r.status==='open'?`<div class="vault-report-actions"><button class="btn ghost" data-report-id="${esc(r.id)}" data-report-status="reviewed">Проверено</button><button class="btn" data-report-id="${esc(r.id)}" data-report-status="actioned">Приняты меры</button><button class="btn ghost" data-report-id="${esc(r.id)}" data-report-status="dismissed">Отклонить</button></div>`:''}</article>`).join('')||'<div class="empty-state">Жалоб пока нет.</div>'}catch(err){box.innerHTML=`<div class="empty-state">${esc(err.message)}</div>`}}const rb=e.target.closest('[data-report-id][data-report-status]');if(rb){rb.disabled=true;try{await call('/admin/reports/'+encodeURIComponent(rb.dataset.reportId),{method:'PATCH',body:JSON.stringify({status:rb.dataset.reportStatus})});toastMsg('Статус жалобы обновлён.');$('#adminReportsBtn')?.click()}catch(err){toastMsg(err.message);rb.disabled=false}}});
 document.addEventListener('click',e=>{if(e.target.closest('[data-view="profile"]'))setTimeout(()=>window.loadVaultPrivacy?.(),100);if(e.target.closest('[data-view="top"]'))setTimeout(()=>window.loadVaultServerTop?.(),100)});
 refreshVaultNotifications(false);setInterval(()=>refreshVaultNotifications(false),60000);
 const extraStyle=document.createElement('style');extraStyle.textContent=`
 .vault-notify-btn{position:relative;min-width:42px;padding:8px 10px;border:1px solid var(--line);border-radius:12px;background:rgba(120,130,115,.06);color:var(--text);cursor:pointer}.vault-notify-btn span{position:absolute;top:-6px;right:-6px;min-width:18px;padding:2px 4px;border-radius:20px;background:#a6b79a;color:#172015;font-size:10px;font-weight:800}.vault-notice-panel{position:fixed;z-index:1000;right:22px;top:78px;width:min(390px,calc(100vw - 24px));max-height:min(70vh,620px);overflow:auto;padding:16px;border:1px solid var(--line);border-radius:20px;background:var(--card,#171916);box-shadow:0 20px 70px #0005;backdrop-filter:blur(22px)}.vault-notice-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.vault-notice-head h3{margin:4px 0 12px}.vault-notice-items{display:grid;gap:8px;margin:10px 0}.vault-notice{display:flex;gap:10px;padding:12px;border:1px solid var(--line);border-radius:13px}.vault-notice.unread{background:rgba(133,154,123,.1)}.vault-notice-dot{width:7px;height:7px;flex:0 0 7px;margin-top:7px;border-radius:50%;background:#91a985}.vault-notice.read .vault-notice-dot{background:transparent;border:1px solid var(--line)}.vault-notice p,.vault-report-row p{margin:4px 0;font-size:12px;color:var(--muted);line-height:1.5}.vault-notice small,.vault-report-row small{font-size:10px;color:var(--muted)}.privacy-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;align-items:end}.privacy-form label{display:grid;gap:7px;color:var(--muted);font-size:12px}.privacy-form .btn{grid-column:1/-1;justify-self:start}.server-top-list{display:grid;gap:7px;margin-top:14px}.server-top-row{display:flex;align-items:center;gap:12px;padding:12px;border:1px solid var(--line);border-radius:13px}.server-top-row.first{border-color:rgba(166,183,154,.55);background:rgba(133,154,123,.08)}.server-top-rank{width:35px;text-align:center;font-weight:800}.server-top-player{display:grid;gap:4px;flex:1;min-width:0}.server-top-player b{overflow:hidden;text-overflow:ellipsis}.server-top-player small{color:var(--muted);font-size:10px}.server-top-row>strong{font-variant-numeric:tabular-nums}.vault-report-row{display:grid;gap:10px;padding:12px;border:1px solid var(--line);border-radius:13px;margin-top:8px}.vault-report-actions{display:flex;flex-wrap:wrap;gap:6px}.vault-report-actions .btn{font-size:11px;padding:7px 10px}@media(max-width:700px){.privacy-form{grid-template-columns:1fr}.privacy-form .btn{grid-column:auto}.vault-notice-panel{right:12px;top:68px}}
 `;document.head.appendChild(extraStyle);

 const style=document.createElement('style');style.textContent=`
 #v-progress .progress-hero{display:flex;align-items:center;justify-content:space-between;gap:20px;background:linear-gradient(120deg,rgba(112,132,108,.13),rgba(255,255,255,.02))}
 .progress-level{min-width:96px;display:grid;place-items:center;padding:14px;border:1px solid var(--line);border-radius:18px;background:rgba(128,145,120,.08)}.progress-level span,.progress-level small{font-size:10px;letter-spacing:.12em;color:var(--muted)}.progress-level b{font-size:32px;color:var(--text)}
 .master-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:16px}.master-item{display:flex;gap:12px;align-items:center;padding:14px;border:1px solid var(--line);border-radius:16px;background:var(--card2,rgba(120,130,115,.05));min-width:0}.master-item.is-done{opacity:.72}.master-item-icon{width:42px;height:42px;flex:0 0 42px;display:grid;place-items:center;border-radius:13px;background:rgba(123,145,116,.13);font-size:21px}.master-item-copy{flex:1;min-width:0}.master-item-copy b,.master-achievement b{font-size:14px;color:var(--text)}.master-item-copy p,.master-achievement p{margin:5px 0;color:var(--muted);font-size:12px;line-height:1.5}.master-item-copy small,.master-achievement small{font-size:10px;color:var(--muted)}.master-meter{height:5px;background:rgba(130,140,125,.15);border-radius:10px;overflow:hidden;margin:8px 0}.master-meter i{display:block;height:100%;background:#83977b;border-radius:10px;transition:width .35s}.master-achievement{padding:16px;border:1px solid var(--line);border-radius:16px;min-height:150px;display:flex;flex-direction:column;align-items:flex-start;gap:7px;background:rgba(120,130,115,.035)}.master-achievement.locked{opacity:.58}.master-achievement-icon{font-size:25px;width:44px;height:44px;display:grid;place-items:center;border-radius:13px;background:rgba(123,145,116,.13)}.master-achievement.unlocked{border-color:rgba(125,151,116,.5)}.master-report-form{display:grid;gap:12px;max-width:620px}.master-report-form label{display:grid;gap:7px;color:var(--muted);font-size:12px}.master-report-form .btn{justify-self:start}.empty-state{padding:20px;border:1px dashed var(--line);border-radius:14px;color:var(--muted);font-size:13px;grid-column:1/-1}
 @media(max-width:700px){.master-grid{grid-template-columns:1fr}.master-item{align-items:flex-start;flex-wrap:wrap}.master-item-copy{min-width:calc(100% - 60px)}.master-item>.btn{margin-left:54px}.progress-level{min-width:76px}.progress-level b{font-size:25px}}
 `;document.head.appendChild(style);
})();
